export const input19Ex1 =
	"r, wr, b, g, bwu, rb, gb, br\n" +
	"\n" +
	"brwrr\n" +
	"bggr\n" +
	"gbbr\n" +
	"rrbgbr\n" +
	"ubwu\n" +
	"bwurrg\n" +
	"brgr\n" +
	"bbrgwb";

export const input19 =
	"bgbuuw, brwbg, gbrw, uuugwrw, buurwrrg, gwbgw, wgrgb, rru, ubgu, uww, wubbg, bww, gruu, wurggb, rbwb, ruubb, urbbrrgb, ugg, brr, rbrrbrbb, bur, urwg, gwwu, rbwg, bgg, uguuuwu, ruuu, wwgwub, rbrg, grrgbrb, wbwbww, buruug, rrgg, gbgwwwrb, wgwwbg, wbggb, wbgrg, b, ubbuww, grw, ru, rgb, uuggwbr, rwwwrbu, rwrwwug, wubgw, gw, gwg, buwwb, uwubub, wgw, ggw, bru, bw, rwbbur, brbw, rgrwuwb, grr, gubrw, grgw, buw, uurg, uur, bbug, wbug, buug, gbrbu, u, bgr, brbbwrg, uwwbb, bwbbwr, bwru, wugwgg, rbbrug, bgbgu, wrbb, brbbwwb, gwbwgu, bub, gwbbbr, uuw, rbrrgw, wuug, bguuug, uurgwuu, uwb, bubg, urrb, grrg, wubr, rbgurww, ugw, wbub, urw, ggbwgg, rr, ggbbub, wbrr, rwrr, wub, gu, rgrub, wgwbub, gguu, rubbrg, wr, bggwb, uwwbggr, gwu, rwbb, wbwur, wuuur, rwg, bbrgb, guww, rurbgrr, ggb, bbwgggb, rur, wwuwu, gbb, grug, grugr, rbguwwwu, ggrrr, wbr, bbg, bwrwwu, wrb, guruwu, uuru, gbw, wwrwggug, gwww, bbw, uwbrg, wuwb, bbgb, wrr, rg, rgr, buubgbrr, rbuu, wbwww, guuwr, gbbg, gurgr, wrgwuu, gurwbb, bgrbw, rbw, rbwwww, rgrb, gub, guw, wgg, gbrbbu, bb, rggg, wb, rurrbrrw, wwubg, gbwgbu, uwuurr, wgbgu, bg, buwu, ugugrw, wwrg, wgurgbu, rrggwg, ugrrg, wrbu, ugrbubgg, gbg, brruwuu, ruuw, wgb, wgubw, urb, wwb, bwrwug, brbb, gbbbwr, grwbbr, wbwgbu, ugbwb, rrgu, ruub, rrrb, wug, rwu, rubbbwu, bbwwgu, wgbrr, guwbr, ggr, rbrw, ggu, uurw, ub, uguru, uuu, bgugu, uru, gr, gur, gwb, wur, grwwugbr, gwrugu, rgwbr, bbgwu, rwbbbrg, bbuu, gg, ruw, ubgb, bubrbb, ruwwr, wwg, gbr, bu, rgg, wwr, wugbrwu, uu, brgwg, bbrbu, ubgruu, uubu, wgr, bbru, uwurr, wubur, bwgu, rbuw, gbwb, rug, ugrguwrg, wwrrg, bwu, grgub, uwu, rgguwbg, gwrbg, urbbbr, wbu, wubb, rww, wuww, gwr, rwrwwg, bbr, ugwuu, wurr, guuwurgb, urugb, bwrbu, ruwbrbu, bwurg, guu, gwbw, wrrbrrw, wuugw, gbwr, ggurg, ubu, uug, gugu, rguuwg, gug, brg, rgu, wrgggu, urruu, uwbgb, wbbbwg, rbbug, wgwg, bbrg, bbggrwb, brwr, wbgrwur, rwwugbu, uwbwgbw, buwg, ubr, guguub, rrubr, rrr, wgrwr, rgruu, rrwr, uggw, wwwrw, uw, ubggwg, bgur, gbu, rrw, rbgrgbw, guugrrr, gugw, uub, bwb, wbrrbr, ugu, rb, bbu, guuggbub, uwr, bgw, rwuruu, wbru, gbrrr, uguu, wbrw, ugbb, wuggr, wbb, ugrww, grg, bgb, rugguub, ug, urg, gwwur, ugwb, gbguu, grbgwbgu, brgggw, gwrru, urur, ruu, bbbwurw, w, grb, brb, rrb, ruur, rgw, ggwg, rruwwur, ugr, wuwwrwg, gwrr, bbgru, ubb, wbbbb, wuu, rrg, wggb, uwww, bug, rrww, ggbguru, wuw, gru, ggrwr, wrbbgru, uwrwb, ugrw, rrgwr, brwb, gww, wubw, wggr, wrww, bbwrr, uwg, wgru, ur, wwu, bugwru, gugguw, wbw, rrwrgr, rurbbu, rwb, bbb, wrgugr, buu, bugrru, rw, r, bwwr, www, gbgwbu, brggbu, ww, gwrrb, gwgw, rwwbgbr, bwr, rggwb, wwrrrr, uwwrb, rbb, bgbrwbbw, rrgr, rbr, bgbbgbb, wrbrb, rubr, guwr, urr, wrw, wurubguw, rwr, ubg, uwwrrgrb, uugwwwgu, grrbg, wru, ugb, br, bgurw, bggb, rrwruw, bwrwu, wwbr, bbww, bggr, rbg, wgu, bruu, gwbugu, gb, rrgrgbb, wrg, grbwwb, bbgwgbru, bgu, bubb, wrgru, rrub, ggwgu, wuwubub, brwrw, ubw, wbg, gugubbu, ugwwurgr, gggb, wgwrggr\n" +
	"\n" +
	"wuubgwbggwbgwugwubgwrgwuwrbwwbbugrruwrbwuubgwgugubbuwg\n" +
	"ubugubbgggbwubwwuguguuguugrbuuuugrbwuggbbgrwrb\n" +
	"wrubbuwurwruruwrgbbrrbugrwruuwugbbwgwwrbwbwwugrrurugwuwubwg\n" +
	"burgrgrrburrggrwubrrurwgbgwwwbrrbggbruwbbgbbruwuwbw\n" +
	"gwguwgururuwwrgrbwgrwuwurgrwugbuguwubwbbggurruwwgwrgbwbwg\n" +
	"uwbwwrrwwwwbwgrggrurwuggwwbwubbbgwbbwwwuwguurwbrguwgbubrbr\n" +
	"uuugrgrrrgwugbrrggbbgburbgwuubbbwuuuurwbruuuwwrg\n" +
	"wbubwururruguwwurbubgwbgbwwuwuuwrubwbbwrgwgwrggr\n" +
	"gbbwbruuubbrwuwburggrrgrbrrbrbbwbbwubruwbuuwuwbuwwwgrrbbwg\n" +
	"uwuuwurgbwgurrwgrrrurbwwwrbuburrgggbwrbgrububgguugggbbwuw\n" +
	"uwbrrwgwugrgrbggbgurbbwuuwwrrwugbwgwrrrrruu\n" +
	"rwgrbgwurwbuuwwrwggbwgruggwgrrgbgwuurwwbub\n" +
	"bbubuugbwbwwgwbrrwgwuwugbwbrbbrwwrbrgggruw\n" +
	"bbwwugbbubwbbgwrwbburrgwbrwwuguubwrrguwrgrugrgurgrrbru\n" +
	"gguggwrwggwrbburubuubuwwwruwbgwbbuuuuurbbrurb\n" +
	"buwgbrbrwwgwrgbgrwbruugwbrrwbrurrgubbwrrggrwubgwbrrw\n" +
	"rurwwuwububrguwgwgbrwgggwggwbgrurggrbbruruurwuwwb\n" +
	"rggwwwurbgwbggubbuwrwubgwwbbbbggwwgguwrguwuu\n" +
	"wwuuubbuwggguurrrwgggrrbwwwwurwgwugwbrwurgubbgwuuuwub\n" +
	"gguuwgrgrugrrubuguwwuruwbbwgbwugruwggbbugwwgggw\n" +
	"bgwbgbrrrgrruurbrruwwgbrrrbgwgguubbrbgwwrburbbwubggr\n" +
	"rbwbwbgrbuwwbrwwurbubggrwwugwgbwrwwgwwrrbgbwbbgwug\n" +
	"uwgbbwrbgwrwrbubuuugbgrurbwwwwbgwbrgrwuuguu\n" +
	"gbgbwuwwrrrbwbuguwguwrrbuuwurugrwuwrruurubwg\n" +
	"rgrguugwbrguuggwruwwrrbrgrgurbrbwguruwubgbwuubu\n" +
	"wrwwggbbgrbuwburubgrgbbbwgbgwburubbwgubwrbbwgbg\n" +
	"brgrbburuuuubugwwbrrrguuurgbuwbgwwrbrbbrbubwrbrrgrgrru\n" +
	"grgrwbuwrbbrwrbubbrgugwuwruguuugwbrrgwburgrb\n" +
	"rgrbubbuguubbbwgbrwgrggubwwwwgbubrbubgbgbwwuuggwr\n" +
	"gggwugbrbgrgbwrugbrwrburbgbwbwwubgbburbrbugurwbbwg\n" +
	"gguruwwuubggrrubwwuurrgbgbgbbuubwbbbgwrggwbrgugurwgrubu\n" +
	"urbgbuwbrwgrguwguwbuggwrrgwrgwwgbrbwruuubbwugg\n" +
	"rrurbwruwwugbbwbrurbrwrguuguwugrbrbruurbuugggurruggwgr\n" +
	"ggrrgrwwguugbgwwwrbgwrbrruurrubrgwggbrwbgbug\n" +
	"urrubbuwurwwwuuuuuugwggwwrgurrrwbuwgggurbug\n" +
	"wrbgwggrbuubwbbgubbwugbggbuwuurubbgwuwbgwgurwwwrwr\n" +
	"wggburuuwuubbbuwbgrgwuuubggbrgbuwwgguwrbwguwuuuwrur\n" +
	"rbguuubwbbuubuggwbrurgbbwuuwwgwugwwrurguguw\n" +
	"burrbugwbgwubbguwbbbbgruwbubuwrgrggbwguwg\n" +
	"bubbrbwgwgrurrbrrwggruggrguurrwrgwrbgwbbgwgu\n" +
	"rrwbbwubruuwrbbwubgrbuwurwrwugbrbbruurwbwurg\n" +
	"brrbwguurgbrbwrrurbgwwgbrgggwwwgrgggrwubgubbbrgwuwuugwrgbwg\n" +
	"wbbugbwrbuubugwbwubggbuggrgurbuuuurbbrrgbbwg\n" +
	"rwburbbwwbwurgwubbgbgbggwbgwugurggbbwgggwub\n" +
	"wgwbrrrubwgwwwwwbwugbgggwubguwggrggruwrubuwbbb\n" +
	"wgurbbguugbbrwrwuwwbbbrguggwurgruruggbuggurubwrgu\n" +
	"rrgwwwrgrgwuuuwrgubgrgwugrbuwwbbwurwubrurbuugwbubrgwrbuwg\n" +
	"brgrbggrgurrgbwurwrwgbggwrrrwwrbwruuuwrbbrwbwu\n" +
	"wguururrrwrrbbrrrugrwuuruubrbgrgbwurwubrubbuurbb\n" +
	"wrbrugrgrrubguurbgwwrrrgbrgwbwuurguurwgurrrruu\n" +
	"grwuwggbwrubgbwwguwrwbbgruwbwwuuwggbwgurwgbggbwgbwwr\n" +
	"uwugurwrwgrbbuwgrgbwuwbgwgugwbggugruubuwgwbwr\n" +
	"bwwguggwuuwuwuwuwubbrrgbbwbguwwrbuggbgrrgwwwuuwrgggurwbbu\n" +
	"grbbuwrrrwwuwuwrwgguruubbgwgwbbbuuuggburguurrbbubwbgrguuwb\n" +
	"gwbuuuuugrubgguuuuwbgrbbgbbrbwrgbgbwwgwurugbugrwrbrwbwbw\n" +
	"rrwbwgbwgbrwgrubwuruurbgugrrwwgwgwuwrgubggubruwubuwgugbbw\n" +
	"ugburbuuuubwwwwrwrbruwrbuugubrbrubwwbgbuubu\n" +
	"bwwrbwwgwgrwrwuurrubggbbrwrbwwuwwurugbrwrbbw\n" +
	"gbubgrwbugwguwgrrgbruuguggruburbwgggrbgrbgrbwguwrrgrrbu\n" +
	"wrbbwwuugbwrgruubbrbwubuugugbrurrwwbbburruuwubwrgrrubwgw\n" +
	"gbwrbbgbugugggruwgrgbgwbgrbrrurruuwwrugwwbgwgwrbwb\n" +
	"urggbugwugbrrwugrguwrgrwbbrgwwggrbubggbuwugrb\n" +
	"wrugbbgggwrrbbbuuurwgbwburrrwrrrwbrbbgwwrwuu\n" +
	"uuwgwrbgrwguwggbbubugwugurbwrwbbgugbugurbggubwruguwrbbbgu\n" +
	"bwugbbwbbguggwrugwgwrbwgwuuwbwwrgrurubwwgguwgrrburrgrubbg\n" +
	"wbwrbruwgbgguwubgubwgbgwugwwwbuwubuurwrrggbwg\n" +
	"rwbrbbrwbrrrugrgbgrgbrrrbggrbgbgrwrrrbgubwrgrwrrgwbbb\n" +
	"bwgggbuguggugbwrugbrbbgguwrguuwgrugugbggwurrb\n" +
	"bggrbgburguuurbbrrrrwguuuguwgguurrwwwuwrggwrrrubr\n" +
	"ubugbrwgbbgbggubbguubbuuwugbbgwwrbrbgbgrwuruububbg\n" +
	"gbrwuururrgrbgwbgugggbbugruuurwbrwugwgurwuugwbwg\n" +
	"rgrwwgrwguugggbguruuwrugwrwuwwwgbbruguruburwbrwgurbu\n" +
	"uurgbuwubgwwrbbuwuwggbgruubbrgbgbggwwwbrbrugrbrgrgrbww\n" +
	"brrbwbubrgbwubwbrbgbbwggrrrwwbguwuuwrggrrwbggugwgbug\n" +
	"bugurrbwbgbrbubbbrubbrgwbggwgurubbubwrggrbubbgg\n" +
	"ugwggggbwrbgwubggguuwgrubwrwbwurrrbuuwurgbbbbrbgb\n" +
	"rurbwuwggrwbwrrwrrbgrgbugbwgbrrwuwguruuurbgurbgwrb\n" +
	"bubrwrbwuburguwwgbbggururgurwrrgrwwurrbbbguwugwuwwwurr\n" +
	"bbubgggwbrbwugwbuwrwbwugurrgwbwbwwgrbgubggrrugrbru\n" +
	"wgbguggrgrugbwbrwrrrubbbbgwurbubbbwurwwgwgbru\n" +
	"urbwrugbgrugbrbbrrbwwwrwbbuugbrurwuurgurguuubbbwrbgburubw\n" +
	"wrwbwbrrbugubrwbwrggurwrrwugrruwbwrwuwgrburgguwbw\n" +
	"bruggwgwubwrbrrggwbrrbbrrbwrbwgbrrwggbbbuuuwwbbg\n" +
	"gbbrgwggbbrbguuburwrwbgbgrwwwwrwrgbrwwwbbbrrwgbbbbuurgrw\n" +
	"grbubbbrwbwbwrgrugrrrgurgrbugbbbbrwbwrurbuwwbuwrwwubgbwrg\n" +
	"guuuugrrrgrbrbuubugubwuugggugguuuubugggwbuuubwggbb\n" +
	"bbrgbugubgrgbbbgbrwbbwbwbururuwwgrbwwrwgubbuu\n" +
	"wgwrwuwugbbrwggbwuwwgwwbgbbwwrwgruruubuugwugrbbbgr\n" +
	"ruuwugwwwurwguruururbrurwbubuguuuggwuwwwwuguggrug\n" +
	"ugbwwrbuwbguugrbgwbguruugbbwwggrugbgguwbgbrbu\n" +
	"grwuguuwgggrurrbrrwgwbwrbubrrbwgrwbgwbbbuwggbbwg\n" +
	"uuwuwwwwwrgwrbubruwbbbwurrrubuggugbrwbrrgwrgr\n" +
	"wruwgugbuuwwrbwbwwbuwrrbrwgwburwgrwwwubwbgbwrbgbggrgur\n" +
	"buuubbwwggubrwubgbbugbggwuurbwrgrggbgruwwwbrugwub\n" +
	"rwbguuruuubuuurbrubbrubbrrrgbrbwwgbbggwbwuwbubbrurbbrrgbu\n" +
	"ugbrwgguurguwbgbuuubbugwubbrrbgbrrubrubugbubrrrwbrrubgg\n" +
	"guwugrgrrguubuugbggwgbuwuugwurubuubguwrburrbgbwwguwurrwgbbwg\n" +
	"wrrrurrurgbggguurbwrrubbbwurrbwbbbgrrbururrbrbbr\n" +
	"wubuwwurugbbgbrwrgwurbwbrgggwwgugugruurggbwubwuuwru\n" +
	"ruwgwubwggwrgwwubuwuuuuggbgrgruuuuwguggwrr\n" +
	"buggwrwwgrrurruwbrbwgrrubwbbwuuwggrurubbwrrwbggggrrgrbw\n" +
	"wrgrburbbggbguuggbubbgrwbubbwwgrrbrbuuruuuwr\n" +
	"uwuuwbgubrwwgruwgbgugrbuwuggrurrbwubbwbrbrru\n" +
	"wwbbbgbbwrwbwbbwrbwrgbgurrurgbwwrbgrwgbgurgbubrgwbgbbugbur\n" +
	"urbrgrbbuwuubuugwubrbguburwgbgrrgwgwgbwgwrgbggwbw\n" +
	"wbgbuuwggurrrrbwbbbggbuugbwrwrruwwuwwbbgrwruuugwwwguwbbubwg\n" +
	"rruurgbbbrwbugrwuuguguwggwrwrgwuuubuwbbbrurubbw\n" +
	"bgugrbrbggrrrrgbwwbguuruwwrrgrbwurugubwwwgrrrbuwb\n" +
	"uuwuururgrgrubuwubruugwbbbuuwurrwruubrwrwubrbbwrrbgbgur\n" +
	"rwugwgbbbbwrbgggrwbgbugubbgrububwgwrbrbuwgguggurbrurwgrb\n" +
	"ggbuubgbrrrbrbgwgrrgwwwwbwwubwwwgbwwrwggwrbubbgbwg\n" +
	"rbugurrbrrrburwbwwgwbrgburwwwgwubuwgggrbrbwbwwrbrbwur\n" +
	"uwrguuuguggbrwwubrgruwrbrggwuwwbrrrbbwgrrrbrbuubgbuugwr\n" +
	"rrgbbgubbrwwbbbwwgugwgrguuuwguurbwgugburwrwgwwwg\n" +
	"bburrwrurwbbwurbguuurrwurrwbbggwurgrbbrgggbbuwwbrwrruubgbwg\n" +
	"rrubbuwruwwururwbwuwwwrwrwwubugwgrggrrubwgbwuwwbwgbbgb\n" +
	"urbgrwgbubbwwgrggrugububuggwurubguwurwwbwg\n" +
	"brwrrrwubuuugwguwubggwuwgwwbgwgurubgwbrwbuw\n" +
	"gwruurbugrbwggbrbbwwgugwrwbrgrbggwurrwwwbgwbww\n" +
	"bbbrrwggrrwubrgbrrgrwwgbbbbbgbuwwgwugrrrrwwguwbgw\n" +
	"bbuugwguguwurrbgbrbgwrwrbrrguuurrwubuwgurgwrwgr\n" +
	"bwgbgggbgrbgbrwubbbwubwwrgggbwrgbrwwguruggrwwbugrwru\n" +
	"wubbbrgbwuwburrrgrubbgwrrugrgrgrgwbwrggggwuurbwggrgwggg\n" +
	"bubrrugguwruugwuwuugbwgwbwgbwrrbugbguwwgurgw\n" +
	"wwgbggrggbwuuuwugbgubgwbrugrwurwwbbgwbwg\n" +
	"grbbwwuwgbbgwuurubgggugbugruguuwrwbguwguwuggbgubug\n" +
	"wgruwruurbwubrwubgrwbbuwgbrugbbrwrgwrbgwbggggwurugburuwr\n" +
	"urrwbgguwrbgugwbrrbgbrbrbrruuburugwgugrgubrgrwgurbbwg\n" +
	"gbbwrubuwubwubuurrbbggbrbbwbwrbuuwubwuwubuwguruwrurbw\n" +
	"rbrugbuubrbrurwuuwurbrburugbgbwuruwurwbururguuwruu\n" +
	"ruurwrguwgbguwrwggbrubwwbrubgwgubgrggbrguuwrrurrrgrbubr\n" +
	"uwuuugbgwwwrbguugrgugrwubrrgrbuwggrwbrrrrrgrgurrbrbbwg\n" +
	"ruggrwrwwrbubgrwrwrgurrbgrgbbgrrgwugubrbbgrrbuuwwrwurrrb\n" +
	"gurgrbwbgwwgbbgrbrbubuuwrwuubuubgwbwbrbrbbguuuwgwugrwbuug\n" +
	"rwgbwurwwgubrgggrgwrgwbwrwrguubrggwwuurbgr\n" +
	"brrrbburgbrbugwggrubgbgwrbugwuruubgbbuggrbgubrrubgw\n" +
	"gugrgrurwbwurrrburwbwruggubrbururwwgwrrrrrgburugwugb\n" +
	"ugbuggbrbguugbwrgwrwbwbwuggrgwrbgrbwwgwuwbrgwgbbrgbgrbw\n" +
	"rrwggwgwuubuwrgrubggrgwbbrbgbgwwwbgbwrguubguurugurgrbb\n" +
	"bwggwgrgbrrrguuurugrwgubuuruurwuwwbwwrwwgbbrrbwbwbbrrbbguu\n" +
	"ubrwrrgrrgwrwugwwurgrubrwbrwgguurgwbwwwrrggbrbbguuuuugugwbwg\n" +
	"bbwbgugrurburwugrrwbwguugrwurrbbbgwbrugbgbrwrgb\n" +
	"wgbuwgwwgggbgrbwguwgugwguuuwurgubwgwururwwrrguwww\n" +
	"gwwbwuugwwwguwurugwwgrubbubbgbubrbwurwrbuuwur\n" +
	"rrwuwgbbbbwrgwururbgrbggbugrgrrwwgrgrrbwwwggrrgwwbggwgu\n" +
	"urrwgggrgbrrbbgbbuubrurbrubwwgggbugrbugwrbuuuwwburwurrrbg\n" +
	"wruuugggrggbwggbguwbgrbwgguurwwrbrrugwrrgubrbgrbbgb\n" +
	"wbburrbrgwrwrwwrrwwbbgbrurgrrguggrrugwubugwr\n" +
	"uwgguwwbbgwwuwrwrwrwwggbwubbuburburwggbbwg\n" +
	"uwuwwuggbwrrbrrwuugggbwgrgugwgwrwbgrwggggwwggrrggbbru\n" +
	"bbuggrrurbrbuuurbrwwururubbrguuurbrugurwwwwwbbwwgbbuugrr\n" +
	"gwrwgwwbgrrrubbruuguwgurrrrwurrwurrbuuuurrggbwg\n" +
	"wruwbuuurwwuruugubbuguwrurwubwbbuwrrrgrwub\n" +
	"bururrubgrubrggwrgrwugburrubwgbrurgbwwrbugwgbbgugrrb\n" +
	"wwburwrwbgbgbggrwwurgrgubwwgburgbbgbrwwrurrrwuwwubgr\n" +
	"ggurgwwrrruwwgbrrwugubwwuurwrbbbrrbguggugubggruwbwbrrbu\n" +
	"wugrbwbrrgwwwrubwwugubrbwwbwbbwuwugugubuubrurwwwgbwgrbwg\n" +
	"rwurugbruugbwgrwurrrwrbuwrwgurgrgurgrwwwwwbub\n" +
	"uuwbruwgrrurbbuugwbwrrwubbbwuggwrubugrgubbbgrrrrwruu\n" +
	"gubburwwrrgwbbwwbubwwbrrggwwbwwbwwwubggguuwuubwbgrrrb\n" +
	"gwrugggwuurwbwugrgwuuwgrwurgbuwgwwurugrbwbwwrgbbuwggu\n" +
	"gubuugbwgbwgbubgugwrrrwgubwgrbuwwbwbbugbrbrug\n" +
	"urbgrbwurburrrbbrgbwuubgugwgbgrrbbubrugbbbggwgrgguwbuwgb\n" +
	"rguwwgrrrbwrubuwgrwgguurbbbguuurugbguwwuugggwbrr\n" +
	"brurwuwgrwggrwrwwwwrbwgruruwuwwwugrwugrguuguubbgggb\n" +
	"bwrbgbrrwgwbrbbuggrbwrwggrbwgrwgugbguwbuurrb\n" +
	"gwgbwuwbgugrwbgbbwrubwuuwwugrugrurbbbwrgwur\n" +
	"uwugbubguugburbbrwurwwgbuuwugubwbbgggbggbgururr\n" +
	"grwuubuwwbgwubwubuwurwrgbuwbwruwguguwgrrrbuwuwwrwbrbrwr\n" +
	"urbubuuwbwgggwgrrwgbrggbrgbwrwurrubbbrwbrrbugbgubwg\n" +
	"wbgugrwgwwrwbwgwurbwwbguuwwbrgwuggrrbugubuuuub\n" +
	"bgbwugrgurgbuuuggwuubbrrggbbbugwugggguwwgb\n" +
	"wrwrburrbbbgbubugbgruguruuburrgwwrbwbwwggbgbbgurbw\n" +
	"burrrrggwubgwuwwbrubbwuwguugrwwgrwuggurwrrwrrrburu\n" +
	"rwwubgggwgwgrrrbubbggrwrwwgbwwgguwguugurbbgwbgbburw\n" +
	"bwugwwrrugurugbrgwbbwurrggbuwbrgurrbugwwrrwugrwgrwu\n" +
	"wugubugwubwrguuuwubbrggrruurgruwwrgwbbbgbrwwbrwrbguubguwrb\n" +
	"uubrbgurugugrbwwwwbrurubbgruubbuubrubgwggu\n" +
	"rwwrrggbrurwbrrguwbwgbrgrgbbbrbuuuwrbgrgggrbbwbwruwwrwuw\n" +
	"ugwgrrbugrrwgwwwbggwbbrgruuwwruurrugwbwg\n" +
	"wububbuugggruwrgbggbwrguwbuwbbwuggwwruurwurwbrwbb\n" +
	"gubwgwwgbgwuwbuugbgwggruwwugrrbubwuwrrburgwgrgrrrurggbbrbw\n" +
	"rwrgbwrgbrbrugbwbgwuuwgrwbwrwwurburgubbrgguugbugwggug\n" +
	"gwgbruwuguggwguwgguwbgbbrruubbwbgburbrugug\n" +
	"wbuuguuwrrguuburbbbwggubbggbwggwurrbubguwrrubbgbbggububwug\n" +
	"urwrwrubbwbwwuuurubgruwggbrgwuwgwbbuwbrurwgbwuruurggwrrbgu\n" +
	"bwbwwgbwbrgrgwwrrrwubrwbwrbrgrwugbbubgrgbwgruububwgru\n" +
	"ubrwrgrrggwgrgwrwbubbbgwrwwugbwubrrbrguwbubgrbwbwg\n" +
	"wrrbrwrbgwbrbuwbgubuubgububrbburbwrrwwugbwgw\n" +
	"grwgubbuuubrbwwrurwwugwubrbbbrruwuubbgguggrwrrwbw\n" +
	"rrbgbwurgrrrwrrwgruwbugggrbrgruubwrbuwgugruguuwwbbrub\n" +
	"rrgbgwwgrbrwuwgwwrwwggurubuugrbubbwrbbrrbwuw\n" +
	"ugbrbgbbgwgbrubrbrurrwubuggbbuuggrgrbrbgrgbubbuubggbwg\n" +
	"gwugbrrwrwuwrrwbrbuwrwuuuwrbwgggrrbwbwwgbgrruguuuwbu\n" +
	"urrurubgbggurgwuurwwggugwubrgubrgrbwuwwbbbugwbwbrrbrbgbur\n" +
	"uurbrwwbwrbrbuwwgguggwgggrwwuguuggbubgugrwbwbgubggrurgbwggg\n" +
	"bbuuwwbrwbwwrwrgwrugubbgbrgggugwuuwggwwgbwggubbrguwbbbwuwb\n" +
	"bwwururbbbgrrrrwwbwgubrbwwggurrrrwrbugguurwbuwuw\n" +
	"rbbgrruwrwubbrugrbrbrwgrbwwrbrbggwbgbuwgwwur\n" +
	"wuuwggwubuggwbgrrrwubwbrrwwurggrurwwbggwuubbwg\n" +
	"uwggbgbbbwbugwubrubbubgbwgwrugurwwbrgrrgbwgbubbgrrgrwrb\n" +
	"uwrwbwggwburwwuggbuguurgrbwbbgbggrbrrbrbburwurruwbgrbwub\n" +
	"bbwuurwwurubbgbwbrurbgwwbbwggwurrugbbbugruurbwggrrbrr\n" +
	"gbuwubbgrrwbbguruguwgbgrugrwwugrrwrrwuuurwgurrrg\n" +
	"grgwbbgbbggbbrbbrrbuwgwwguwwgugubwuurbgbwubbrbwburrb\n" +
	"ururrwurubrgwbugrggggbwbggguwwbbwubbggugwbgugwbuwgb\n" +
	"ubuwubugrwwwwrrbugbrwrbgugrgrwgwrurwbgrubggurwggwrugrub\n" +
	"ugwbugbwgurubwggrwgrrubrgbbwbbbbrgugubuuwwbbrbgu\n" +
	"wwbubbubuwwguuburwugwruwggguwbgrruuwrbubbuubwwrw\n" +
	"gbbugwrrgrubrbgggbugbwubrubbwuwrurrgrbgbbrbgrwwgruw\n" +
	"buuwugbuguuwurugburbrrbrgrgbbbrurgrguwguwugugbbwbgrwwww\n" +
	"gwgwrrugwugwbggrrgrbuwgbgburwbggwwgugrrwgwuwwwwrubwg\n" +
	"bwrgwwrurrbbubuwwrgurwbrrubgrwuwubrugwrbuwwrubwuwrbbb\n" +
	"gbuwuggwrrbubgubgrbbgrburrrwwrwgwwgrgurgwwrbbgbbuwuu\n" +
	"rbrgwgwwuwbrgrggrgrwwugbrguuuubrguwrbuggubugwrgbbbbwg\n" +
	"rbburwgugwwurgrggbugrrrrwwrbgrburgrgbugbugguruwwwrurb\n" +
	"bwwwwwurbugwruwuwurubwggwrbbwgrwurbwwbuwruwbruuugwgbwgbb\n" +
	"wwguuburgwrubrrbgbguggguwuuwwrrwuuruuuurwrbubgbu\n" +
	"rburbbwgbgwbbburgbugrrwugugugwubgwwruuwwgwrubww\n" +
	"wrggugbgrgbwuurgwgbguwurrrbggbwggrgbwururbgwubbwg\n" +
	"rguwuwugbubbrwuurwrgbrbuwrbbrrbgurbwgbbwbg\n" +
	"bbgwrrbuwbugrbbgburwbwrguwbbrgwbubwrrggbbwrubuub\n" +
	"bbugbrrurbrgrubrugugbubbwwwwbuwbgrgbbbbrbu\n" +
	"brrwburgwbuugggwwuwwwurrbugrrurruwgwgbbbwrubgbwg\n" +
	"gbwwbrgwwugbwwbuugbwrbuugrrbbrgrrwuururbggurugggrwurgr\n" +
	"wubbbwrrgwwgrrgwgwgrbgwuugugwbrugugubbwbruuubuuuurru\n" +
	"gubrwgubwgruugwbgbugwuubruuuuurbwwruuruurwrgruuuwuurwwwr\n" +
	"ugwwrwgbburrwrbwgwrrrurbuuburgruruuwgugggbbwwwrrrggrbu\n" +
	"gwggbbbwuwbwurugubruubwburgwrbrwwbgruurbbgrbrgbwgugg\n" +
	"brgbrwbbgbrwwuwgwrubbuwwruugwbbburuwbwugugbwrgbrg\n" +
	"urwbggwgggrrbbrubburwrgrgrggrbubwwbrbuburwwbub\n" +
	"brwbgrggrgugrrwurwgrurrbugbrwrbgwubgrbgrbwgbggrwuur\n" +
	"bbbrgwwrbrurwuuwrgrrguubbruubuwwrrgrruruwwwrgwrububgbgbg\n" +
	"gwubrgwwuuuwwbuuurgwrrwbgggrgwgurgrgwgugrrgrruw\n" +
	"wurguuwrrwwggrbugwruwuwwgrugwbgbgwrrrugbruug\n" +
	"bgwurwrrbwrrugbwwwrwwggbbruwwrwwubwwurwurrgwubrbrgbwbwuww\n" +
	"ugggbrgrugubugurrbgwgrbrbwbwuguruwurburgwggrwwguwbbgr\n" +
	"bubrgrubbrgbwwgburbrrbuugwrrrbwruruwbgwgrggwwbbguburwruww\n" +
	"wggwbbuwugrgwwbrrbwrgbwrggbrggurbwgwwbuwwrgbbrwwbrurrurubu\n" +
	"ubuggwuwuwbwuurgrrbugrgwurwuuwugrbwwgrwwwbwrugurgrbrwggrug\n" +
	"rgwwbuwbwbwrgwgbuwwwrbgruubugwrgbgwburuwwugwwrburubggbug\n" +
	"uuwwwrwrbrrrrbwrguurgruwggrubrwgguwbbubwbgrruwrurgwru\n" +
	"ubwuwurbrggrbrgubbuubbwrbgbuugbbwrgurrbgbrrbwgrurubwggwgu\n" +
	"wbgwbuwbwrggggrbwguwggwgrwwgrbwbwgwwwwgbggurggrggbwbbwbgwg\n" +
	"rruruwuruuurggwugruuuwgruggruwgwwwurwwrwuwrwugwrbg\n" +
	"rrbrubrwgbbgwrwwrrrrbuggrwburrrwbrgggggrrgguwgr\n" +
	"gbubgguwrrwuwruwrrgrrbwbrwguugurbwgurgwwrbguubgwrwr\n" +
	"grgrrrbbgbrbbuwwruuwguwggwgurubuubbbrgrrgwgrgbgguwbuubg\n" +
	"wrwurbwgwgugggbuwwruwbgrurggbbbuurgrbrugbrgw\n" +
	"rrwgrwggbgbggurubgrbwbugugbgrwrgwwbrrggwbbggwrrgw\n" +
	"urgwubgugwbuwgrguurwwrbbbguurwwwwwwgbrwubggwubbwubgbwbg\n" +
	"bgbgrubwwrwggrwwbbbbbwwgggrbuwrggbbubbugbwg\n" +
	"ugwbgwguruuwrrgwrugwrrburwburbgrugwgwrbbrbuwww\n" +
	"ubuuuugggrbuubwgrwggwuguuugbwggubbgrrwggrbgrbugbbgu\n" +
	"rwrubgurgugggrggwuwrbbruwrguwuubggwrrgrgbguwwbbrggg\n" +
	"brubgbwwbwbubguuwurgbubwburwubbruuuuurubguruuwgwbwg\n" +
	"ugubrrrugrgwwggubuwrrrbubrbuubruggugggubwwwbrruwuww\n" +
	"rgbugbwggwugurrrugbrwubuwbbgbububwrggrrgrug\n" +
	"wrwrrbbwuubgrbbubwgbggwwburgwurrgrubbuwwwgggwgwr\n" +
	"bbuwgwbggbguwwwuwguuwguwbubruwwgwgwwbwuurbuubgbbgubuwurgg\n" +
	"gbbbuwrguwrwuuwrrwbrburrubgrbgwggurrbgubgu\n" +
	"wgurrwrwgwguburugggggwbggbuugguwgrubwbrrbgurbwrwbbwrbwb\n" +
	"rwbrggbwruurgwbwrwgwrwbrbugbrgwuwuwrgbwgubuw\n" +
	"gwrbrrrrbrwwrgbbrggrbrrubgbwbbwbgbggbwugrugrbbru\n" +
	"gwgggbbrbgrrbgubwbbubwwuggwgwrguuwuuwuwgrwgwurrbrb\n" +
	"wuwwbggrwuwburuwburwbrbwbbbbuggrbwwwrrburgwrgbrwbrburbbwu\n" +
	"ruurbbwbuubuuubuguuurggurrggwububugggurrgwruuw\n" +
	"wrrrgrgbguruubgbgurbuwgwrwwbggubwwrbbbwrrbwwbwbrbuguuw\n" +
	"wggrrbwgwgrwwugwwugbwwubrwwrwgburuwugwurgrbwwrwbrguuwwugwb\n" +
	"bgrwwugbrugurbgubwrgwwbrurgguwrgruurrwgbuguguugr\n" +
	"rrbwwrbgwubugurruuwbbuwgbwubgbbrwuubbruwwuwbguggwbuwrwrbr\n" +
	"gbuuggrugurbwugggurwggguwugrwwgurgguruubugrwuubuubgwbwgw\n" +
	"uwbggbgbwrrwurbwggrrwrrwuwbbwrwugugbrwbrrwrgbbg\n" +
	"guggbburgrbwrbwuwgurrwwbwwuuwbbgwgbrgwwrguuuurrubuwguu\n" +
	"uwbrurwwrwwbwubrrggrugwurgbwbubwgwwrggrrubbuugwbwggg\n" +
	"bwwubwugggwbugurwurgggwbwrrrubugrggwrwbrwgwwb\n" +
	"rbgubwwwugugggbguwbrwgubbrbbbwbwwbwbrbgurrru\n" +
	"ubuwwrbbbuguurrbruwwgburuurwruubggwwwrbwguwww\n" +
	"grrbgbrubguwwrbbggugbbwuwrwugrgubbwgurrurr\n" +
	"rwwubgrbrrbbbgrbbbbugwrguuwgwrgwrrgrwuwrwbuwuwubgwrbrbuub\n" +
	"rbbubgbbgrbrguwgguurbububbugbbbwbrrrrgubwgwuwggwb\n" +
	"gwwururguwwbbbbwuwwrrrgrugwbwbbuurbwwwuruwwwrbbbuuuguggr\n" +
	"wwbrbwrgwwbbrugbuugwwggwgbwwguwuugbgbwuugb\n" +
	"ggggwwuguurubugrrwguubwruwrruubbrbbubbwurwgbuuwbb\n" +
	"rrrbguuwguuwbrruguguwgwbwrgrrrgwubwrbgbwwgwrwugbbr\n" +
	"wgrrbwrbbbbuuugwurruwbgubbubrubrggruubwrgwurbrwgrwrgr\n" +
	"brwuuwrrrrurrbgrwgrrgrrbbubwbrrwggwrbburrwrggwgbuuru\n" +
	"wburugurrugrwgbrwwrwggugbugububwwgubwrwbuwwgwwguu\n" +
	"rbwbbwrbwbwwrggurbgubwuwrrbrgbgwwbbugrugbbrrgwgrugruwrug\n" +
	"bgguwwurwwwugwgwwgbbbgwgbrurggbwwwuwubwbwwuwwwwr\n" +
	"gwbrwbgrwgbbbwrurwbrwgwuuwbgrguuuwrbrrurrrbgrbrggurwgrugw\n" +
	"uububwbugruugbubwrwrbbwwrbwbggrwrrugggwwwwubguwg\n" +
	"rwwburugbwbggwbwgrbgugugrguguubgbrwbbwggg\n" +
	"bgubbwbuurbwrurwurbuubuggbwurbgwrgggrbrbwbwgrggbr\n" +
	"gurwbugbuuubgggrgurrbwbwgbrgwrwgugubbugwwbrrgrwuuwwr\n" +
	"urgbuugrubugrgbgubwruubrrrubrgbrgwgurgggrbrrwuruuuubrrg\n" +
	"wurrrrruwrwrwruwwggwwwuguuurrurubrgbuwgrrubbubrubgbrgu\n" +
	"gbubbbwggwwrrbuwrwgbrgbuugwrgwrgwwuruuubrwbwg\n" +
	"gguggrrgwbgbbrwwrgrbgbrrrwgurwgrubgbgwwbgbwrwubbw\n" +
	"wwwrggrwrgrwbrgbbgrrbbubgrrwwbgwubbugwwwruwrwrwgwuwgbub\n" +
	"rwgwrggwrggwgugbugrguwrgbwgbwwgwrwbrububguruubwg\n" +
	"guubbbggurbggwuwwbwrruuwububgurwbwruggbgbw\n" +
	"wgubwwgggrurwbwrbbwubbubrrwgrurbggbgubrwgubrwrrgwubu\n" +
	"rgrrwggwbuwuurwrwwwbuwuwggrbrrubggbwurrwwwbbwugu\n" +
	"gbgbgggggrbrwrgrwgubuwbggwbwgurwuguuwrwuugrgwgr\n" +
	"ruurgwwbgbgruwwwuurburwuwuubrubbbgbguwrrbburbubbuwb\n" +
	"bgwgwrbrubwugubugrugrrggwbbrrwwggwrwbgwbwrurbubrbubgg\n" +
	"gggbruwggwurugbbbuwrbwruubwbwrburwwruurgwruururrwuuwgrbbg\n" +
	"rwwbwuggguuruggrruwruwgwrgrbrwwggrbrbuwrgrggbwrwb\n" +
	"grbbgbbgbrrbwruggrwburgwwwuwrbbgbuwgwbubwu\n" +
	"wwwwgwbbbrwugugrbubgguggbuggbuugbwruwrubbubggwgrgugbbwg\n" +
	"uwbgwrbubrrrugwbuburuwbbggwgbrggrgruwruwgrruu\n" +
	"brurgwgbuwuwwgbuwgruuwgbgwwbubbbrbrbwrwugwuuggwg\n" +
	"rgruwrrwgwuugrbubggbbrgbuuwwgwbbwbburgrbggrurbuuuguw\n" +
	"uuwrgwubrrbwbrwrbgburgbrwbwbgbbgrgrrwwrbrrrwbwwbburwgw\n" +
	"wwbgbbugbbwbguurubuggrbbrbuubuwbbburwbbruwwugu\n" +
	"wbuugruruwwruuguwbwrwgrgbwuwurrgbgbgbguguwwbugu\n" +
	"rgrruuuwwrrbbuwugwwrgugbbggrwgbrbggururgbwg\n" +
	"urwugubuwbrwrbbrbbrgbgbwggwggwguwwubwbruwwu\n" +
	"grbugbgurwgrgubrwgrgbubbrggbwbgwbbwgrbrwwrrgrrug\n" +
	"wwwgbbwburwbwgbbuurbgrwwrbgbbwbbwwbgrrrggrrgbug\n" +
	"uwuuggguwrburrgrwgburwbuuggbbwubgwgrugwgguwg\n" +
	"wgrurrbrwugrbrubrwrgrurbururwgrbrgbwuwguwwwbggr\n" +
	"wrbrugrbwggwbwbwrbgbuurwrrgwwgugrruuguuuubwwbrguwgww\n" +
	"ugwwbwwuwgwuwruurwwubwbrurggbbruwruwwwggruguuwrrwgbwurgr\n" +
	"gurrrgbgbrbbrrbrwuuuwgubgrgwggrwrbrgubwrubbur\n" +
	"rwubgbwurubbbwggwuubrbbrgwuwuruwuwbugwgrbbr\n" +
	"brrruurubwwwruwggugbgrwrwugububwwwururbgub\n" +
	"uuwubrbwguuubbbguuwguwwwurwrugwbruwuruuwrrgurggurwwbbbwrbb\n" +
	"ugbrrggwbwwububbbuwbugrruuugugwbwwrgbrwbrwgg\n" +
	"gbugwbrwbuwwruubbbbwbbbbrwrrbuwgrrgburwrbbrwgwwru\n" +
	"wwbgburbruurbrbwbgwbuuwrwgbwruwwwgrbrwrgrrbugrr\n" +
	"wruwruwwrubuurbgbrgbwgrwggrbwgwbrwgugrurgruwb\n" +
	"guurruwubuuwubwrubwguwurgburburwrwggbuwbugbburbg\n" +
	"bwrugbuuwbgurgwwuwrurbgwgggrbgbrbubugbbruwggur\n" +
	"buuurggbgwuwurgbwgrgwwrbwuggrguugbgrwgrugr\n" +
	"rbuwwrbgwbwbbwguwuwubrwwrugwguwurubguwrugwgggr\n" +
	"rgugbbwrbrgbgwbbrbuwrrgrwwuuuwuwbrrgbrrubgbwbwg\n" +
	"bwwbrburwwwrrrruwgwggrrrwgugruurwwgubwurwrbgbw\n" +
	"ubugbwruuubgbwwbgwbruuruurgrubwwbgrurggbrguuuwwrwbwwrg\n" +
	"gwwwbwuwrggrbwurwwruwuwrbwgrbrwwbwwrrbuubb\n" +
	"bbwgrwwurrgwwrwrrrbwbwrbguwwwurggrrbbwguwg\n" +
	"wubwggrrbrbugwbrbrrubuwwbrbubrubrgrgbgbrubwbwg\n" +
	"uubwruuwrwrgrrwwbgwbrugrgrwwbuwgwbwwuguwrbgrgruwwbbwg\n" +
	"uggrwbggruubguggwbgrbbggrurrwwruggrrbubwuuugggwugbwgwwgbg\n" +
	"bwguwrrbbubgrgugwbwrburugrrgwbuwubbububwugurrwubuwb\n" +
	"gubbugbuwguugugwbwwbwguwuggbburubbwrwgwwubuwbguurbrgrwrrbb\n" +
	"brbbwguwrwuwwbburwwuwgrrwrbugruuwbuwbwurbubgbr\n" +
	"rwuuguuwurgbbgwrbuwgwuurrggrbwwrgruuruurbw\n" +
	"gwrbuwwwgrugwbuurwwbggburruruuubburwwurruwbubugrgbru\n" +
	"rgubugguwwbwbgrrrwbuggggwrrggbururrbgbgbrbuguguggwb\n" +
	"bwwwwrbguuwgbuwuwbbrbugurrrgwuguugwrwwrrugburwuruwubwg\n" +
	"grwrggrgubguwgbuubuwggurwwrgrbwubwrbwrrugwuwruuww\n" +
	"rggwwrrubbguuwgwbwrrbuububguubwwbbrrbbwuwbrugrbrwwrggr\n" +
	"bbgbwbwbuubbgrwgggwwuuuwrwbwbggrbgwbwuwbwbuwb\n" +
	"uurgrrbgggbrggrurgbwrugrgbgurgruwbwwbwuuguww\n" +
	"wrwguwrrwugwggbrrrbwwuguwrwgugwgbbbbrgwwgwrurgwggrwbwbgr\n" +
	"ruwrurugbwrgrbrrrrwbuubwgwggrrwwrwgugbugbgwww\n" +
	"wbruwuuuugbbggruwwrrgrbbwwwrwwgwwguwbwgbwg\n" +
	"wgbgrwwgbruwbrrbgrburwwwgwrgwwwwwwgbggbgbugbgruuwrubugbw\n" +
	"rbrbbwuubuguuubguurbrurbugrgrubbrgugrbguwwwubwruwguwrgu\n" +
	"wwrwggugrgggwgrrrwurwbwgubwgbrrgrgurbrgbwuugugbwrrgbwg\n" +
	"wwwgguurwgrwgwrbwbuwrrguwuugwrrgubbuuubrubgbbrw\n" +
	"brbbbwruubuwrurgwbgrbbbugrrrbwrgbbwruwwbrgbugrwwgwuru\n" +
	"grurrbgubgrgwbwruuwrgwwgbugbwbbbuubwrrbuguwgubrbgwgwwbbr\n" +
	"wwrbguwuwbuwbguburwrggrrwbbgurruwubwbbbwrgwb\n" +
	"rgrgrbbguuguwwwrburrrgwggwrbguwwbrgbbwguwgbgugbw\n" +
	"wrwrugggbgrwwgwrwruubugugrrrurubwrrrgrgrurub\n" +
	"wgbbwgbrugbrrwbuuurrubruurrbwuwguwwgrggwrguwrugbwg\n" +
	"wgwuuwbwbuwrurugbuubuwuugguwguwuggrggubbrbuubwu\n" +
	"wwwugbrgrgwbbwggubbgwrgwwugwrrrrbbwbbrgugugwggrub\n" +
	"rrbgwggwugbrwurbrbbbbwrwrrrgruwrbbgugrgrrwrgrururgggw\n" +
	"rwrrwgwbgbwrbrburuuruggwrwugubgbuwwbwguwbugbgwrggrbrbug\n" +
	"uubuwuuwbwwurugbggbubbgrrurgwubbrwggwbbwwrr\n" +
	"burgwbwbgwbuwgubwgwgruwbuguwrgbbggugbgrwggbrrug\n" +
	"bgbwbrruuuwbbrrgwuwbbrbgbrbbwwbbuubwuuurug\n" +
	"rgwrbruwgbugruwgrrugbgwwugrguuuggggrgububbbrgwgb\n" +
	"rgubbrruwubgwgrgrrbgbubuuubrbburbrrwwbgwubuurggwurbg\n" +
	"grrwbwguwubuuwrgrwbuurbwuwbrbrugggwgurrwwbwrg\n" +
	"wgwbwbgwrbbrrrrubuurrwwggurwurwrrwgrbugrwgwguubgrgubguw\n" +
	"brrgwbbrwrwggbbbwwwruugwwbguggbwbwbrwbubbbbbbbgwgrbgrgb\n" +
	"rbwbbrrrwbuwrbgwrrrrruguugrrbuwbbgrrrbwguwrubggugrubugwgg\n" +
	"brbgbgbwwwbwurrrwwguguggrrwgbbgrrwwuwbgwwrwuguuuwubbrgb\n" +
	"grbgbgwrrwbuubgbrrwuuwurggurwbbwgbrubgbrrgwgb\n" +
	"wuggrrwbbgbbbbwrururuwrgrgurgbwwbwbwwwgbgrbubbrurgu\n" +
	"grgbbguurbgrwwbwwgbrruuwubrwbrgbguwrbrrrgbubwurbrbruwruuw\n" +
	"buubrbrwguwggbgbgrgruuuwrrbwuuubgrggrbgbggrrbbgr\n" +
	"rbwwbbuubbrrwwbbwgrwrgbgrrggrubrbgwurbrrgwwrbwgbwg\n" +
	"ruggruwuruugggwbggwwgrbgubrbgbwgubrbwgggrurbgrbgrgwugr\n" +
	"bugwurwbrrruuwgwbruwgrrwrrurrgbgbuwgggrrwgrrbuuggbuub\n" +
	"brwguuruubwggrgggurbrwwrbwwrugbbggurwubggwuugubgbrg\n" +
	"wrrbggurgburbgrwurbgbrburbbbuggwrrwbbgwbuwgbbwgwwg\n" +
	"uwwbwbbbgguggrrgwgrbwbwwgrgwwwgwububgbugwbggguubwg\n" +
	"urrwrgrrbgubbwwrwbrgbwburbwwbrwgrrbwrugwugrg\n" +
	"ururguwwbwbwgrwuugwbrgwrwbrwrwrurwwrwgugrggbwrrbbbgrwwguu\n" +
	"gggbbwrubgwwgugrbwbwbbgubrrbggbgwguuuwwbuwgruwbwu\n" +
	"urbbbgbubrbbwgubwwwrrrwwggwuuggbwgruruuwrurbrugbb\n" +
	"wrbugwgrbwggrrgrwgrrgurrbuwbggggrwbbbgbwbrrwbuubwg\n" +
	"wbbrgrgrbrguurggwrwgbuguwwgwrwgrrwrubwggbbggbbwr\n" +
	"bwruguburrrruwwrbwwrgbrrbwgwrrwwbbbuwgbgrurrwuugwgrwwbgbb";
